### ISSUE TITLE
Aufgabenverteilung

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/DHBW.Labyrinth#1]
**Aufgabenzuordnung** der Aufgaben je einer Person, da die Noten individuell bestimmt wird.

**Comment by micrem** [comment]
Aufgaben:

1. Algorithmus implementieren
2. Adjazenzmatrix implementieren
3. Adjazenzmatrix aus einer CSV-Datei laden
4. Unit-Tests schreiben

**Comment by MasterZydra** [comment]
Erledigt **siehe ReadMe**
